name: Build and Deploy Docker Container

on:
  push:
    branches: [ devops-nv ]
  pull_request:
    branches: [ devops-nv ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t s2s-frontend .
          # docker build -t s2s-frontend ./docker -f ./docker/Dockerfile.stage

      - name: Checkout backend repo
        run: |
          git clone https://github.com/ita-social-projects/SpaceToStudy-BackEnd.git backend

      - name: Build Docker image for backend
        run: |
          cd backend
          docker build -t s2s-backend .

      - name: Run Docker container for backend
        run: |
          docker run -d -p 8080:80 s2s-backend
 
      - name: Run Docker container
        run: |
          docker run -d -p 3000:80 s2s-frontend

      - name: Wait for app to be up and running
        run: |
          sleep 30 

      - name: Test application 
        run: |
          curl http://localhost:3000

      - name: Test API via reverse proxy
        run: |
          curl -X GET http://localhost:3000/categories?name=&limit=8&skip=0
    
      - name: Test API with status check
        run: |
          http_response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/categories?name=&limit=8&skip=0)
          if [[ "$http_response" -ne 200 ]]; then
            echo "API test failed with response code $http_response"
            exit 1
          fi

      - name: Install ws package
        run: |
          npm install ws

      - name: Install wscat
        run: |
          npm install -g wscat

      - name: Test WebSocket connection
        run: |
          wscat -c ws://localhost:3000/socket.io/

      - name: Test WebSocket connection with parameters
        run: |
          wscat -c ws://localhost:3000/socket.io/?EIO=4&transport=polling

      - name: Stop Docker container
        run: |
          docker stop $(docker ps -q)
